#pragma once

// OpenAuto Version Information
// This file is automatically generated during build

#ifndef OPENAUTO_MODERN_VERSION_H
#define OPENAUTO_MODERN_VERSION_H

#include <string>

namespace openauto {
namespace modern {

// Version numbers (date-based: YYYY.MM.DD)
constexpr int MAJOR = OPENAUTO_VERSION_MAJOR;
constexpr int MINOR = OPENAUTO_VERSION_MINOR;
constexpr int PATCH = OPENAUTO_VERSION_PATCH;

// Version strings
constexpr const char* VERSION_STRING = OPENAUTO_VERSION_STRING;
constexpr const char* BUILD_DATE = OPENAUTO_BUILD_DATE;

// Git information
constexpr const char* GIT_COMMIT = OPENAUTO_GIT_COMMIT;
constexpr const char* GIT_COMMIT_FULL = OPENAUTO_GIT_COMMIT_FULL;
constexpr const char* GIT_BRANCH = OPENAUTO_GIT_BRANCH;
constexpr const char* GIT_DESCRIBE = OPENAUTO_GIT_DESCRIBE;

// Convenience functions
inline std::string getVersionString() {
    return std::string(VERSION_STRING);
}

inline std::string getFullVersionInfo() {
    return std::string(VERSION_STRING) + 
           " (branch: " + std::string(GIT_BRANCH) + 
           ", commit: " + std::string(GIT_COMMIT) + 
           ", built: " + std::string(BUILD_DATE) + ")";
}

inline std::string getBuildInfo() {
    return "OpenAuto " + std::string(VERSION_STRING) +
           "\nBranch: " + std::string(GIT_BRANCH) +
           "\nCommit: " + std::string(GIT_COMMIT_FULL) +
           "\nDescribe: " + std::string(GIT_DESCRIBE) +
           "\nBuild Date: " + std::string(BUILD_DATE);
}

} // namespace modern
} // namespace openauto

#endif // OPENAUTO_MODERN_VERSION_H
